name: Pylint

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r ./requirements.txt
        pip install pylint==2.17.5
    - name: Analysing the code with pylint
      run: |
        if [[ $(ls -A ./demo) ]]; then python -m pylint ./demo/; else echo "./demo is Empty"; fi || true
        if [[ $(ls -A ./src) ]]; then python -m pylint ./src/; else echo "./src is Empty"; fi || true